### ISSUE TITLE
Linked List Implimentation

### ISSUE THREAD

**Issue by anmol27katyani** [anmol27katyani/JMOC-2019-scripts#1]

**Comment by imrishabh18** [comment]
Hey, i want to work on this issue. So, do i just need to implement a linked list data structure in python, Right ?

**Comment by anmol27katyani** [comment]
Yes, You directly jump into the issue, Make a PR with implementation. :)
Over the period of time, Work on other issues as well

**Comment by anmol27katyani** [comment]
Completed
